
import { Option } from './types';

export const WAKTU_OPTIONS: Option[] = [
  { value: "", label: "Pilih waktu..." },
  { value: "pagi hari", label: "Pagi (Morning)" },
  { value: "siang hari", label: "Siang (Afternoon)" },
  { value: "sore hari", label: "Sore (Evening)" },
  { value: "malam hari", label: "Malam (Night)" },
  { value: "fajar", label: "Fajar (Dawn)" },
  { value: "senja", label: "Senja (Dusk)" },
  { value: "golden hour", label: "Golden Hour (Golden Hour)" },
  { value: "blue hour", label: "Blue Hour (Blue Hour)" },
];

export const PENCAHAYAAN_OPTIONS: Option[] = [
  { value: "", label: "Pilih pencahayaan..." },
  { value: "alami", label: "Alami (Natural Light)" },
  { value: "studio", label: "Studio (Studio Light)" },
  { value: "Rembrandt", label: "Rembrandt (Rembrandt Lighting)" },
  { value: "Butterfly", label: "Butterfly (Butterfly Lighting)" },
  { value: "Loop", label: "Loop (Loop Lighting)" },
  { value: "Split", label: "Split (Split Lighting)" },
  { value: "cahaya redup (low key)", label: "Cahaya Redup (Low Key)" },
  { value: "cahaya terang (high key)", label: "Cahaya Terang (High Key)" },
  { value: "neon", label: "Neon (Neon)" },
  { value: "cahaya lilin", label: "Cahaya Lilin (Candlelight)" },
  { value: "siluet", label: "Siluet (Silhouette)" },
  { value: "sinematik", label: "Sinematik (Cinematic Lighting)" },
  { value: "dramatis", label: "Dramatis (Dramatic Lighting)" },
];

export const GAYA_VIDEO_OPTIONS: Option[] = [
  { value: "", label: "Pilih gaya video..." },
  { value: "sinematik", label: "Cinematic (Cinematic)" },
  { value: "dokumenter", label: "Dokumenter (Documentary)" },
  { value: "vlog", label: "Vlog (Vlog Style)" },
  { value: "animasi 2D", label: "Animasi 2D (2D Animation)" },
  { value: "animasi 3D", label: "Animasi 3D (3D Animation)" },
  { value: "stop motion", label: "Stop Motion (Stop Motion)" },
  { value: "retro", label: "Retro (Retro/Vintage)" },
  { value: "futuristik", label: "Futuristik (Futuristic)" },
  { value: "hitam putih", label: "Hitam Putih (Black and White)" },
  { value: "hyperlapse", label: "Hyperlapse (Hyperlapse)" },
  { value: "slow motion", label: "Slow Motion (Slow Motion)" },
  { value: "fantasi", label: "Fantasi (Fantasy)" },
  { value: "sci-fi", label: "Sci-Fi (Science Fiction)" },
  { value: "realistis", label: "Realistis (Realistic)" },
  { value: "surealis", label: "Surealis (Surreal)" },
];

export const SUASANA_VIDEO_OPTIONS: Option[] = [
  { value: "", label: "Pilih suasana video..." },
  { value: "bahagia", label: "Bahagia (Happy)" },
  { value: "sedih", label: "Sedih (Sad)" },
  { value: "tegang", label: "Tegang (Tense/Suspenseful)" },
  { value: "misterius", label: "Misterius (Mysterious)" },
  { value: "romantis", label: "Romantis (Romantic)" },
  { value: "menakutkan", label: "Menakutkan (Scary/Horror)" },
  { value: "damai", label: "Damai (Peaceful/Calm)" },
  { value: "energik", label: "Energik (Energetic)" },
  { value: "nostalgia", label: "Nostalgia (Nostalgic)" },
  { value: "komedi", label: "Komedi (Comedic)" },
  { value: "epik", label: "Epik (Epic)" },
  { value: "gelap", label: "Gelap (Dark/Gloomy)" },
  { value: "cerah", label: "Cerah (Bright/Uplifting)" },
];

export const KAMERA_GERAKAN_OPTIONS: Option[] = [
  { value: "", label: "Pilih gerakan kamera..." },
  { value: "static shot (tangkapan statis)", label: "Static Shot (Tangkapan Statis)" },
  { value: "pan left (geser kiri)", label: "Pan Left (Geser Kiri)" },
  { value: "pan right (geser kanan)", label: "Pan Right (Geser Kanan)" },
  { value: "tilt up (dongak ke atas)", label: "Tilt Up (Dongak ke Atas)" },
  { value: "tilt down (tunduk ke bawah)", label: "Tilt Down (Tunduk ke Bawah)" },
  { value: "zoom in (perbesar)", label: "Zoom In (Perbesar)" },
  { value: "zoom out (perkecil)", label: "Zoom Out (Perkecil)" },
  { value: "slow zoom in (perbesar perlahan)", label: "Slow Zoom In (Perbesar Perlahan)" },
  { value: "slow zoom out (perkecil perlahan)", label: "Slow Zoom Out (Perkecil Perlahan)" },
  { value: "crash zoom (zoom cepat)", label: "Crash Zoom (Zoom Cepat)" },
  { value: "dolly in (dolly masuk)", label: "Dolly In (Dolly Masuk)" },
  { value: "dolly out (dolly keluar)", label: "Dolly Out (Dolly Keluar)" },
  { value: "push in (dorong masuk)", label: "Push In (Dorong Masuk)" },
  { value: "pull out (tarik keluar)", label: "Pull Out (Tarik Keluar)" },
  { value: "truck left (geser kamera kiri)", label: "Truck Left (Geser Kamera Kiri)" },
  { value: "truck right (geser kamera kanan)", label: "Truck Right (Geser Kamera Kanan)" },
  { value: "pedestal up (naikkan kamera)", label: "Pedestal Up (Naikkan Kamera)" },
  { value: "pedestal down (turunkan kamera)", label: "Pedestal Down (Turunkan Kamera)" },
  { value: "crane shot (tangkapan derek)", label: "Crane Shot (Tangkapan Derek)" },
  { value: "boom up (boom ke atas)", label: "Boom Up (Boom ke Atas)" },
  { value: "boom down (boom ke bawah)", label: "Boom Down (Boom ke Bawah)" },
  { value: "jib up (jib ke atas)", label: "Jib Up (Jib ke Atas)" },
  { value: "jib down (jib ke bawah)", label: "Jib Down (Jib ke Bawah)" },
  { value: "steadicam shot (tangkapan steadicam)", label: "Steadicam Shot (Tangkapan Steadicam)" },
  { value: "handheld shot (tangkapan genggam)", label: "Handheld Shot (Tangkapan Genggam)" },
  { value: "tracking shot (tangkapan mengikuti)", label: "Tracking Shot (Tangkapan Mengikuti)" },
  { value: "aerial shot (tangkapan udara)", label: "Aerial Shot (Tangkapan Udara)" },
  { value: "drone shot (tangkapan drone)", label: "Drone Shot (Tangkapan Drone)" },
  { value: "orbit (mengorbit)", label: "Orbit (Mengorbit)" },
  { value: "360 degree shot (tangkapan 360 derajat)", label: "360 Degree Shot (Tangkapan 360 Derajat)" },
  { value: "arc shot (tangkapan melengkung)", label: "Arc Shot (Tangkapan Melengkung)" },
  { value: "whip pan (geser cepat)", label: "Whip Pan (Geser Cepat)" },
  { value: "vertigo effect / dolly zoom (efek vertigo / zolly)", label: "Vertigo Effect / Dolly Zoom (Efek Vertigo / Zolly)" },
  { value: "zolly in (zolly masuk)", label: "Zolly In (Zolly Masuk)"},
  { value: "zolly out (zolly keluar)", label: "Zolly Out (Zolly Keluar)"},
  { value: "rolling shot / barrel roll (tangkapan bergulir)", label: "Rolling Shot / Barrel Roll (Tangkapan Bergulir)" },
  { value: "first-person POV (sudut pandang orang pertama)", label: "First-Person POV (Sudut Pandang Orang Pertama)" },
  { value: "over-the-shoulder shot (tangkapan lewat bahu)", label: "Over-the-Shoulder Shot (Tangkapan Lewat Bahu)" },
  { value: "rise (naik perlahan)", label: "Rise (Naik Perlahan)" },
  { value: "fall (turun perlahan)", label: "Fall (Turun Perlahan)" },
  { value: "float (mengambang)", label: "Float (Mengambang)" },
  { value: "spiral in (spiral masuk)", label: "Spiral In (Spiral Masuk)" },
  { value: "spiral out (spiral keluar)", label: "Spiral Out (Spiral Keluar)" },
  { value: "dutch angle / tilt (sudut miring)", label: "Dutch Angle / Tilt (Sudut Miring)" },
  { value: "fly through (terbang melewati)", label: "Fly Through (Terbang Melewati)" },
  { value: "time-lapse (selang waktu)", label: "Time-lapse (Selang Waktu)" },
  { value: "circular pan (geser melingkar)", label: "Circular Pan (Geser Melingkar)" },
  { value: "reveal shot (tangkapan pengungkapan)", label: "Reveal Shot (Tangkapan Pengungkapan)"},
  { value: "low angle shot (tangkapan sudut rendah)", label: "Low Angle Shot (Tangkapan Sudut Rendah)"},
  { value: "high angle shot (tangkapan sudut tinggi)", label: "High Angle Shot (Tangkapan Sudut Tinggi)"},
];
